FROM node:14 as build-stage

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

# NGINX SERVER
FROM nginx:alpine
EXPOSE 80
COPY nginx.conf /etc/nginx/nginx.conf


COPY --from=build-stage /app/build /usr/share/nginx/html