name: Produção

on:
  push:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn package -f api-voluntier/pom.xml -Dmaven.test.skip=true
      - name: Rename jar
        run: mv api-voluntier/target/*.jar api-voluntier/target/api.jar
      - name: Compact jar
        run: gzip api-voluntier/target/api.jar
      - name: Copy jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: api-voluntier/target/api.jar.gz
          target: /tmp
          strip_components: 2
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: "sudo systemctl stop api && gzip -d /tmp/api.jar.gz && sudo mv /tmp/api.jar /var/www/api && sudo chown www-data:www-data /var/www/api/api.jar && sudo systemctl start api"
