name: Produção Frontend

on: 
  push:
    branches: [main]
    paths:
      - frontend/**


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 14.17.5
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.5'

  build:
    
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@main

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build with nodejs
        working-directory: ./frontend
        run: CI=false npm run build 
        
      - name: Compact Build
        run: tar -cvzf prod_build.tar.gz frontend/build/
        
      - name: Copy file zip
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_FRONTEND }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: prod_build.tar.gz
          target: /tmp
          strip_components: 0
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: check
        uses: actions/checkout@v2
      - name: Update Service Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_FRONTEND }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: "sudo systemctl stop frontend-voluntier && cd /tmp && sudo tar -zxvf prod_build.tar.gz && sudo rm -rf /var/www/frontend-voluntier/build && sudo mv /tmp/frontend/build /var/www/frontend-voluntier && sudo chown www-data:www-data  /var/www/frontend-voluntier/build && sudo systemctl start frontend-voluntier"
